baseURL = "https://bd.scoiatael.dev/"
languageCode = "en-us"
title = "Scoiatael's braindump"
theme = "ananke"

[params]
  favicon = "favicon/favicon.ico"
  github = "https://github.com/scoiatael/braindump"
  background_color_class = "bg-light-blue"
  featured_image = "/images/rohro-clark-Jgdbp3pPj9Q-unsplash.jpg"
  description = "Abandon all hope, ye who enter here."

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = -110